'use strict';

// Explicitly disposable PostgreSQL only. No dotenv, seed data, Firebase or
// media-provider calls. Cleanup is restricted to this run's synthetic IDs.
const test = require('node:test');
const { before, after } = test;
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
let databaseName = '';
try { databaseName = decodeURIComponent(new URL(process.env.DATABASE_URL || '').pathname.slice(1)); } catch {}
const allowedDatabase = /^edulock_qa(?:_[a-zA-Z0-9-]+)*$/;
if (!allowedDatabase.test(databaseName)) {
    console.error('REFUSED: account PostgreSQL tests require an explicitly named edulock_qa database.');
    process.exit(1);
}
for (const key of ['COURSES_SEED', 'CATALOG_SEED', 'CATALOG_SEED_1', 'CATALOG_SEED_2', 'CATALOG_SEED_3', 'ALLOWED_DOMAINS_SEED']) delete process.env[key];
const db = require('../database-pg');
const tracked = { students: new Set(), requests: new Set(), courses: new Set(), licenses: new Set(), activations: new Set(), registrationDevices: new Set(), deviceOwners: new Set() };
const uuid = () => crypto.randomUUID();
const id = kind => { const value = uuid(); tracked[kind].add(value); return value; };
const identity = () => ({ uid: 'qa-account-' + uuid(), email: 'qa-account-' + uuid() + '@example.invalid' });
const query = (...args) => db.pool.query(...args);
const row = async (table, value) => (await query(`SELECT * FROM ${table} WHERE id=$1`, [value])).rows[0] || null;

before(async () => {
    const actual = (await query('SELECT current_database() AS name')).rows[0].name;
    assert.equal(actual, databaseName); assert.match(actual, allowedDatabase);
    await db.initDb();
});

after(async () => {
    try {
        if (tracked.deviceOwners.size) {
            const devices = (await query('SELECT id FROM devices WHERE student_id=ANY($1::text[])', [[...tracked.deviceOwners]])).rows;
            if (devices.length) await query('DELETE FROM devices WHERE id=ANY($1::text[])', [devices.map(value => value.id)]);
        }
        // Registration helper chooses its UUID; recover only IDs attached to
        // device UUIDs generated by this process, even if an assertion failed.
        if (tracked.registrationDevices.size) {
            const rows = (await query('SELECT id FROM registration_requests WHERE device_id=ANY($1::text[])', [[...tracked.registrationDevices]])).rows;
            rows.forEach(value => tracked.requests.add(value.id));
        }
        for (const [table, values] of [
            ['activations', tracked.activations], ['licenses', tracked.licenses],
            ['registration_requests', tracked.requests], ['students', tracked.students], ['courses', tracked.courses],
        ]) {
            if (table === 'students' && values.size) await query('DELETE FROM student_courses WHERE student_id=ANY($1::text[])', [[...values]]);
            if (values.size) await query(`DELETE FROM ${table} WHERE id=ANY($1::text[])`, [[...values]]);
        }
    } finally { await db.pool.end(); }
});

async function student(account, extra = {}) {
    const value = id('students');
    await db.createStudent({ id: value, email: extra.email || account.email, studentId: 'qa-' + value, name: 'Synthetic existing account', active: extra.active !== false, allowedVideos: extra.allowedVideos || [] });
    await query('UPDATE students SET firebase_uid=$1,approval_status=$2,max_devices=$3 WHERE id=$4',
        [extra.uid === undefined ? account.uid : extra.uid, extra.status || 'approved', extra.maxDevices || 3, value]);
    return value;
}
async function course() { const value = id('courses'); await db.createCourse({ id: value, name: 'Synthetic account course' }); return value; }
async function request(account, extra = {}) {
    const deviceId = extra.deviceId || id('registrationDevices');
    tracked.registrationDevices.add(deviceId);
    const requestId = await db.createRegistrationRequest({ email: account.email, firebaseUid: account.uid, emailVerified: extra.emailVerified === true,
        deviceId, name: 'Synthetic applicant', deviceModel: 'QA device', deviceName: 'QA', ...extra });
    tracked.requests.add(requestId);
    if (extra.status) await query('UPDATE registration_requests SET status=$1 WHERE id=$2', [extra.status, requestId]);
    return requestId;
}
async function approve(input) {
    const result = await db.approveRegistrationAtomic(input);
    tracked.students.add(result.studentId);
    return result;
}
async function entitlement(studentId, courseId) {
    const licenseId = id('licenses'), activationId = id('activations');
    await db.createLicense({ id: licenseId, licenseKeyHash: uuid(), studentId, courseId, maxDevices: 3 });
    await db.createActivation({ id: activationId, licenseId, studentId, deviceId: uuid(), activationTokenHash: uuid(), expiresAt: new Date(Date.now() + 3600000).toISOString() });
    return { licenseId, activationId };
}
async function state(studentId) {
    return {
        student: await row('students', studentId),
        courses: (await query('SELECT * FROM student_courses WHERE student_id=$1 ORDER BY course_id', [studentId])).rows,
        licenses: (await query('SELECT * FROM licenses WHERE student_id=$1 ORDER BY id', [studentId])).rows,
        activations: (await query('SELECT * FROM activations WHERE student_id=$1 ORDER BY id', [studentId])).rows,
    };
}
async function accountCount(account) {
    return Number((await query('SELECT COUNT(*) AS n FROM students WHERE firebase_uid=$1 OR LOWER(TRIM(email))=$2', [account.uid, account.email])).rows[0].n);
}
async function sqlFailureAt(match, work) {
    // Inject a real PostgreSQL statement error on the transaction connection,
    // so rollback is tested in PostgreSQL without creating global triggers.
    const original = db.pool.connect;
    let injected = false;
    db.pool.connect = async function (...args) {
        const client = await original.apply(this, args);
        return { release: () => client.release(), query: async (sql, params) => {
            if (!injected && match(sql, params)) { injected = true; return client.query('SELECT 1 / 0'); }
            return client.query(sql, params);
        } };
    };
    try { await assert.rejects(work(), { code: '22012' }); assert.equal(injected, true); }
    finally { db.pool.connect = original; }
}

test('unknown Firebase identity and approved orphan registration never self-create a student or wildcard access', async () => {
    const account = identity();
    assert.deepEqual(await db.resolveFirebaseAccount({ ...account, emailVerified: true }), { student: null, registration: null });
    assert.equal(await accountCount(account), 0);
    const requestId = await request(account, { status: 'approved' });
    const beforeRow = await row('registration_requests', requestId);
    const result = await db.resolveFirebaseAccount({ ...account, emailVerified: true });
    assert.equal(result.student, null); assert.equal(result.registration.id, requestId); assert.equal(result.registration.status, 'approved');
    assert.equal(await accountCount(account), 0); assert.deepEqual(await row('registration_requests', requestId), beforeRow);
});

test('verified legacy email binding changes only firebase_uid and keeps grants, license, activation and suspension', async () => {
    const account = identity(), courseId = await course();
    const studentId = await student(account, { uid: null, email: '  ' + account.email.toUpperCase() + '  ', active: false, status: 'suspended' });
    await db.setStudentCourses(studentId, [courseId], 'qa-before');
    await entitlement(studentId, courseId);
    const beforeState = await state(studentId);
    const resolved = await db.resolveFirebaseAccount({ ...account, emailVerified: true });
    assert.equal(resolved.student.id, studentId); assert.equal(resolved.student.firebase_uid, account.uid);
    assert.equal(resolved.student.active, false); assert.equal(resolved.student.approval_status, 'suspended');
    assert.deepEqual(resolved.student.allowedVideos, [courseId]); assert.equal(resolved.student.max_devices, 3);
    const afterState = await state(studentId);
    beforeState.student.firebase_uid = account.uid;
    assert.deepEqual(afterState, beforeState);
});

test('unverified claims cannot bind a legacy student, including truthy non-boolean input', async () => {
    const account = identity(), studentId = await student(account, { uid: '' });
    const original = await state(studentId);
    for (const emailVerified of [false, undefined, 'true', 1]) {
        await assert.rejects(db.resolveFirebaseAccount({ ...account, emailVerified }), { code: 'EMAIL_VERIFICATION_REQUIRED', statusCode: 403 });
        assert.deepEqual(await state(studentId), original);
    }
});

test('a matching UID can sign in without re-linking or altering a stored inactive account', async () => {
    const account = identity(), studentId = await student(account, { active: false, email: account.email.toUpperCase() });
    const original = await state(studentId);
    const resolved = await db.resolveFirebaseAccount({ uid: account.uid, email: ' ' + account.email + ' ', emailVerified: false });
    assert.equal(resolved.student.id, studentId); assert.equal(resolved.student.active, false);
    assert.deepEqual(await state(studentId), original);
});

test('all duplicate email or UID matches are denied instead of selecting the first historical student', async () => {
    for (const duplicateKind of ['email', 'uid']) {
        const account = identity();
        const first = await student(account);
        const second = await student(duplicateKind === 'email' ? { ...account, uid: null } : { ...account, email: identity().email },
            duplicateKind === 'email' ? { email: ' ' + account.email.toUpperCase() + ' ' } : {});
        const originals = await Promise.all([state(first), state(second)]);
        await assert.rejects(db.resolveFirebaseAccount({ ...account, emailVerified: true }), { code: 'ACCOUNT_DUPLICATE', statusCode: 409 });
        assert.deepEqual(await Promise.all([state(first), state(second)]), originals);
    }
});

test('UID/email mismatches fail closed without overwriting either identity', async () => {
    const account = identity(), studentId = await student(account), original = await state(studentId);
    for (const credentials of [{ ...account, uid: identity().uid }, { ...account, email: identity().email }]) {
        await assert.rejects(db.resolveFirebaseAccount({ ...credentials, emailVerified: true }), { code: 'ACCOUNT_IDENTITY_MISMATCH', statusCode: 409 });
    }
    assert.deepEqual(await state(studentId), original);
});

test('competing verified UIDs cannot both bind the same legacy account', async () => {
    const account = identity(), studentId = await student(account, { uid: null });
    const otherUid = identity().uid;
    const outcomes = await Promise.allSettled([account.uid, otherUid].map(uid => db.resolveFirebaseAccount({ uid, email: account.email, emailVerified: true })));
    assert.equal(outcomes.filter(result => result.status === 'fulfilled').length, 1);
    const winner = outcomes.find(result => result.status === 'fulfilled').value.student;
    assert.equal(winner.id, studentId); assert.equal((await row('students', studentId)).firebase_uid, winner.firebase_uid);
    assert.equal(outcomes.find(result => result.status === 'rejected').reason.code, 'ACCOUNT_IDENTITY_MISMATCH');
    assert.equal(await accountCount(account), 1);
});

test('registration verification is stored only from a verified UID, is monotonic, and cannot be stolen', async () => {
    const account = identity(), deviceId = id('registrationDevices');
    const requestId = await request(account, { deviceId, emailVerified: false });
    assert.equal((await row('registration_requests', requestId)).email_verified, 0);
    assert.equal(await request(account, { deviceId, emailVerified: true }), requestId);
    await request(account, { deviceId, emailVerified: false });
    assert.equal((await row('registration_requests', requestId)).email_verified, 1);
    await assert.rejects(request({ ...account, uid: identity().uid }, { deviceId, emailVerified: true }), { code: 'REGISTRATION_DEVICE_OWNER_CONFLICT' });
    const legacy = identity(); legacy.uid = null;
    const legacyId = await request(legacy, { emailVerified: true });
    assert.equal((await row('registration_requests', legacyId)).email_verified, 0);
    assert.equal((await row('registration_requests', requestId)).firebase_uid, account.uid);
});

test('registration lookup normalizes historical emails and selects the most recent row deterministically', async () => {
    const account = identity(), earlier = await request(account), later = await request(account);
    await query('UPDATE registration_requests SET email=$1,requested_at=$2 WHERE id=$3', ['  ' + account.email.toUpperCase() + '  ', '2026-01-01T00:00:00.000Z', earlier]);
    await query('UPDATE registration_requests SET requested_at=$1 WHERE id=$2', ['2026-01-02T00:00:00.000Z', later]);
    assert.equal((await db.getRegistrationRequestByEmail(' ' + account.email.toUpperCase() + ' ')).id, later);
    const resolved = await db.resolveFirebaseAccount({ ...account, emailVerified: true });
    assert.equal(resolved.student, null); assert.equal(resolved.registration.status, 'pending');
    assert.equal(await accountCount(account), 0);
});

test('mismatched registration UID or email cannot be used for login or approval', async () => {
    const account = identity(), requestId = await request(account);
    for (const credentials of [{ ...account, uid: identity().uid }, { ...account, email: identity().email }]) {
        await assert.rejects(db.resolveFirebaseAccount({ ...credentials, emailVerified: true }), { code: 'ACCOUNT_IDENTITY_MISMATCH' });
    }
    const studentId = await student({ ...account, uid: identity().uid });
    await assert.rejects(approve({ requestId, courseIds: [], maxDevices: 1 }), { code: 'ACCOUNT_IDENTITY_MISMATCH' });
    assert.equal((await row('registration_requests', requestId)).status, 'pending');
    assert.notEqual((await row('students', studentId)).firebase_uid, account.uid);
});

test('restrictive orphan request states outrank approval, while an existing student remains authoritative', async () => {
    const account = identity(), pending = await request(account), approved = await request(account, { status: 'approved' });
    await query('UPDATE registration_requests SET requested_at=$1 WHERE id=$2', ['2999-01-01T00:00:00.000Z', approved]);
    let resolved = await db.resolveFirebaseAccount({ ...account, emailVerified: true });
    assert.equal(resolved.student, null); assert.equal(resolved.registration.id, pending);
    const rejected = await request(account, { status: 'rejected' });
    resolved = await db.resolveFirebaseAccount({ ...account, emailVerified: true });
    assert.equal(resolved.registration.id, rejected);
    const suspended = await request(account, { status: 'suspended' });
    resolved = await db.resolveFirebaseAccount({ ...account, emailVerified: true });
    assert.equal(resolved.registration.id, suspended); assert.equal(await accountCount(account), 0);
    const studentId = await student(account);
    resolved = await db.resolveFirebaseAccount({ ...account, emailVerified: false });
    assert.equal(resolved.student.id, studentId); assert.equal(resolved.student.approval_status, 'approved');
    assert.equal(resolved.registration, null);
});

test('explicit approval creates one student with the request UID and exact course/device grants', async () => {
    const account = identity(), requestId = await request(account, { emailVerified: false }), courseId = await course();
    const result = await approve({ requestId, courseIds: [courseId], maxDevices: 4, notes: 'Synthetic approval', reviewedBy: 'qa-admin' });
    assert.deepEqual(result, { ok: true, studentId: result.studentId, maxDevices: 4 });
    const stored = await row('students', result.studentId), reg = await row('registration_requests', requestId);
    assert.equal(stored.firebase_uid, account.uid); assert.equal(stored.email, account.email); assert.equal(stored.approval_status, 'approved');
    assert.equal(stored.active, 1); assert.equal(stored.max_devices, 4); assert.equal(stored.allowed_videos, JSON.stringify([courseId]));
    assert.deepEqual((await db.getStudentCourses(result.studentId)).map(value => value.course_id), [courseId]);
    assert.equal(reg.status, 'approved'); assert.equal(reg.reviewed_by, 'qa-admin'); assert.equal(reg.notes, 'Synthetic approval');
    assert.equal((await db.resolveFirebaseAccount({ ...account, emailVerified: false })).student.id, result.studentId);
});

test('approval of an existing legacy account requires verification and preserves activation/license links', async () => {
    const account = identity(), requestId = await request(account), studentId = await student(account, { uid: null });
    const previousCourse = await course(), nextCourse = await course();
    await db.setStudentCourses(studentId, [previousCourse], 'qa-old');
    await entitlement(studentId, previousCourse);
    const original = await state(studentId);
    await assert.rejects(approve({ requestId, courseIds: [nextCourse], maxDevices: 5 }), { code: 'EMAIL_VERIFICATION_REQUIRED', statusCode: 403 });
    assert.deepEqual(await state(studentId), original);
    const requestDevice = (await row('registration_requests', requestId)).device_id;
    await request(account, { deviceId: requestDevice, emailVerified: true });
    const result = await approve({ requestId, courseIds: [nextCourse], maxDevices: 5 });
    assert.equal(result.studentId, studentId);
    const updated = await state(studentId);
    assert.equal(updated.student.firebase_uid, account.uid); assert.equal(updated.student.student_id, original.student.student_id);
    assert.equal(updated.student.created_at, original.student.created_at); assert.equal(updated.student.allowed_videos, JSON.stringify([nextCourse]));
    assert.deepEqual(updated.activations, original.activations);
    original.licenses.forEach(value => { if (value.status === 'active') value.max_devices = 5; });
    assert.deepEqual(updated.licenses, original.licenses);
    assert.deepEqual(updated.courses.map(value => value.course_id), [nextCourse]);
});

test('explicit all-course approval uses wildcard and clears former course grants without resetting licenses', async () => {
    const account = identity(), studentId = await student(account), requestId = await request(account), courseId = await course();
    await db.setStudentCourses(studentId, [courseId]); await entitlement(studentId, courseId);
    const beforeState = await state(studentId);
    await approve({ requestId, courseIds: [], maxDevices: 3 });
    assert.equal((await row('students', studentId)).allowed_videos, '*');
    assert.deepEqual(await db.getStudentCourses(studentId), []);
    assert.deepEqual((await state(studentId)).activations, beforeState.activations);
    assert.deepEqual((await state(studentId)).licenses, beforeState.licenses);
});

test('approval cannot reactivate an inactive student or a suspended registration', async () => {
    const account = identity(), studentId = await student(account, { active: false, status: 'suspended' }), requestId = await request(account);
    const original = await state(studentId), originalRequest = await row('registration_requests', requestId);
    await assert.rejects(approve({ requestId, courseIds: [], maxDevices: 2 }), { code: 'ACCOUNT_SUSPENDED', statusCode: 409 });
    assert.deepEqual(await state(studentId), original); assert.deepEqual(await row('registration_requests', requestId), originalRequest);
    const other = identity(), suspendedRequest = await request(other, { status: 'suspended' });
    await assert.rejects(approve({ requestId: suspendedRequest }), { code: 'ACCOUNT_SUSPENDED' });
    assert.equal(await accountCount(other), 0);
});

test('approval validates all courses and device limits before any persisted changes', async () => {
    const account = identity(), requestId = await request(account), courseId = await course();
    const original = await row('registration_requests', requestId);
    for (const courseIds of [null, 'not-array', ['*'], ['bad-id'], [courseId, courseId]]) {
        await assert.rejects(approve({ requestId, courseIds }), { code: 'REGISTRATION_APPROVAL_INVALID', statusCode: 400 });
    }
    await assert.rejects(approve({ requestId, courseIds: [uuid()] }), { code: 'COURSE_NOT_FOUND', statusCode: 400 });
    for (const maxDevices of [null, '2', '2junk', 0, -1, 1.5, 51, NaN, Infinity, true]) {
        await assert.rejects(approve({ requestId, courseIds: [courseId], maxDevices }), { code: 'INVALID_DEVICE_LIMIT', statusCode: 400 });
    }
    await assert.rejects(approve({ requestId: uuid() }), { code: 'REGISTRATION_NOT_FOUND', statusCode: 404 });
    assert.equal(await accountCount(account), 0); assert.deepEqual(await row('registration_requests', requestId), original);
});

test('duplicate historical students also prevent explicit approval and preserve the request', async () => {
    const account = identity(), requestId = await request(account, { emailVerified: true });
    await student(account); await student({ ...account, uid: identity().uid }, { email: account.email.toUpperCase() });
    const original = await row('registration_requests', requestId);
    await assert.rejects(approve({ requestId }), { code: 'ACCOUNT_DUPLICATE', statusCode: 409 });
    assert.equal(await accountCount(account), 2); assert.deepEqual(await row('registration_requests', requestId), original);
});

test('concurrent approvals of the same account create one student and preserve a coherent final grant', async () => {
    const account = identity(), first = await request(account), second = await request(account), courseId = await course();
    const results = await Promise.all([first, first, second].map(requestId => approve({ requestId, courseIds: [courseId], maxDevices: 2 })));
    assert.equal(new Set(results.map(value => value.studentId)).size, 1); assert.equal(await accountCount(account), 1);
    assert.equal((await row('registration_requests', first)).status, 'approved'); assert.equal((await row('registration_requests', second)).status, 'approved');
    const stored = await row('students', results[0].studentId);
    assert.equal(stored.allowed_videos, JSON.stringify([courseId])); assert.equal(stored.max_devices, 2);
    assert.equal((await db.getStudentCourses(stored.id)).length, 1);
});

test('login racing approval cannot manufacture a second or unrestricted student', async () => {
    const account = identity(), requestId = await request(account), courseId = await course();
    const [approval, resolved] = await Promise.all([
        approve({ requestId, courseIds: [courseId], maxDevices: 1 }),
        db.resolveFirebaseAccount({ ...account, emailVerified: true }),
    ]);
    if (resolved.student) assert.equal(resolved.student.id, approval.studentId);
    else { assert.equal(resolved.registration.id, requestId); assert.equal(resolved.registration.status, 'pending'); }
    assert.equal(await accountCount(account), 1);
    assert.deepEqual((await db.findStudentById(approval.studentId)).allowedVideos, [courseId]);
});

test('a real SQL failure at final approval rolls back new student, courses and request together', async () => {
    const account = identity(), requestId = await request(account), courseId = await course();
    const original = await row('registration_requests', requestId);
    await sqlFailureAt(sql => /^UPDATE registration_requests SET status='approved'/.test(sql),
        () => db.approveRegistrationAtomic({ requestId, courseIds: [courseId], maxDevices: 2 }));
    assert.equal(await accountCount(account), 0); assert.deepEqual(await row('registration_requests', requestId), original);
    assert.equal(Number((await query('SELECT COUNT(*) AS n FROM student_courses WHERE course_id=$1', [courseId])).rows[0].n), 0);
});

test('late SQL failure restores existing identity, all grants, license limit and activation', async () => {
    const account = identity(), studentId = await student(account, { uid: null }), requestId = await request(account, { emailVerified: true });
    const oldCourse = await course(), nextCourse = await course();
    await db.setStudentCourses(studentId, [oldCourse]); await entitlement(studentId, oldCourse);
    const original = await state(studentId), originalRequest = await row('registration_requests', requestId);
    await sqlFailureAt(sql => /^UPDATE registration_requests SET status='approved'/.test(sql),
        () => db.approveRegistrationAtomic({ requestId, courseIds: [nextCourse], maxDevices: 7 }));
    assert.deepEqual(await state(studentId), original); assert.deepEqual(await row('registration_requests', requestId), originalRequest);
});

test('failed account lookup propagates the database error and never becomes missing account', async () => {
    const account = identity(), studentId = await student(account, { uid: null });
    await sqlFailureAt(sql => sql.includes('SELECT * FROM students WHERE firebase_uid='),
        () => db.resolveFirebaseAccount({ ...account, emailVerified: true }));
    assert.equal((await row('students', studentId)).firebase_uid, null); assert.equal(await accountCount(account), 1);
});

test('concurrent admin logins without a student row cannot exceed their device limit', async () => {
    const owner = 'admin_qa-device-' + uuid(); tracked.deviceOwners.add(owner);
    assert.equal(await row('students', owner), null);
    const firstFingerprint = uuid();
    assert.equal((await db.registerOrValidateDevice(owner, firstFingerprint, {}, 2)).ok, true);

    const original = db.pool.connect;
    // Widen the real count/insert race without faking query results. With the
    // owner lock the second count waits; without it both logins see one slot.
    db.pool.connect = async function (...args) {
        const client = await original.apply(this, args);
        return { release: () => client.release(), query: async (sql, params) => {
            const result = await client.query(sql, params);
            if (/^SELECT COUNT\(\*\) as n FROM devices/i.test(sql) && params[0] === owner) {
                await client.query('SELECT pg_sleep(0.05)');
            }
            return result;
        } };
    };
    let attempts;
    try { attempts = await Promise.all([uuid(), uuid()].map(fingerprint => db.registerOrValidateDevice(owner, fingerprint, {}, 2))); }
    finally { db.pool.connect = original; }
    assert.equal(attempts.filter(value => value.ok).length, 1);
    assert.deepEqual(attempts.find(value => !value.ok), { ok: false, device: null, reason: 'device_limit_exceeded', limit: 2, activeCount: 2 });
    assert.equal(await db.countActiveDevices(owner), 2);
    assert.equal((await db.registerOrValidateDevice(owner, firstFingerprint, {}, 2)).reason, 'existing');
    assert.equal(await row('students', owner), null, 'admin device registration must not invent a student row');
});

test('simultaneous retries for one admin fingerprint return the same stored device', async () => {
    const owner = 'admin_qa-device-' + uuid(), fingerprint = uuid(); tracked.deviceOwners.add(owner);
    const attempts = await Promise.all(Array.from({ length: 4 }, () => db.registerOrValidateDevice(owner, fingerprint, {}, 2)));
    assert.equal(attempts.every(value => value.ok), true);
    assert.equal(new Set(attempts.map(value => value.device.id)).size, 1);
    assert.equal(await db.countActiveDevices(owner), 1);
    assert.equal(await row('students', owner), null);
});
