'use strict';

// Run only against the disposable QA database. No dotenv import and no Bunny
// calls. All records are synthetic and cleanup targets their generated IDs.
const test = require('node:test');
const { before, after } = test;
const assert = require('node:assert/strict');
const crypto = require('node:crypto');

let databaseName;
try { databaseName = decodeURIComponent(new URL(process.env.DATABASE_URL || '').pathname.slice(1)); }
catch { databaseName = ''; }
if (!/^edulock_qa(?:_[a-zA-Z0-9-]+)*$/.test(databaseName)) {
    console.error('REFUSED: PostgreSQL integration tests require an explicitly named edulock_qa database.');
    process.exit(1);
}
for (const key of ['COURSES_SEED', 'CATALOG_SEED', 'CATALOG_SEED_1', 'CATALOG_SEED_2', 'CATALOG_SEED_3', 'ALLOWED_DOMAINS_SEED']) delete process.env[key];

const db = require('../database-pg');
const { createAccessPolicy } = require('../lib/access-policy');
const registry = { students: [], courses: [], modules: [], licenses: [], lots: [], producers: [], videos: [], operations: [], resources: [], tokens: [], sessions: [], registrationDevices: [] };
const id = type => { const value = crypto.randomUUID(); registry[type].push(value); return value; };
const hash = value => crypto.createHash('sha256').update(value).digest('hex');

before(async () => { await db.initDb(); });
after(async () => {
    try {
        // Tables have different identifiers; all values below were generated by
        // this process. Never delete by a broad date/name/email pattern.
        const deletions = [
            ['active_sessions', 'session_id', registry.sessions],
            ['pending_play_tokens', 'token', registry.tokens],
            ['registration_requests', 'device_id', registry.registrationDevices],
            ['suspicious_activity', 'student_id', registry.students],
            ['stream_operations', 'id', registry.operations],
            ['stream_resources', 'resource_key', registry.resources],
            ['activations', 'license_id', registry.licenses],
            ['devices', 'student_id', registry.students],
            ['student_courses', 'student_id', registry.students],
            ['licenses', 'id', registry.licenses],
            ['license_lots', 'id', registry.lots],
            ['catalog', 'video_id', registry.videos],
            ['deleted_videos', 'video_id', registry.videos],
            ['modules', 'id', registry.modules],
            ['courses', 'id', registry.courses],
            ['students', 'id', registry.students],
            ['producers', 'id', registry.producers],
        ];
        for (const [table, column, values] of deletions) if (values.length) {
            await db.pool.query(`DELETE FROM ${table} WHERE ${column}=ANY($1::text[])`, [values]);
        }
    } finally { await db.pool.end(); }
});

async function student(producerId = null) {
    const value = id('students');
    await db.createStudent({ id: value, email: `qa-${value}@example.invalid`, studentId: `qa-${value}`, name: 'Synthetic QA', active: true, allowedVideos: [] });
    await db.pool.query("UPDATE students SET approval_status='approved', max_devices=3, producer_id=$1 WHERE id=$2", [producerId, value]);
    return value;
}
async function producer({ maxLicenses = 10, maxDevices = 2, maxStudents = 0 } = {}) {
    const value = id('producers');
    await db.createProducer({ id: value, email: `qa-${value}@example.invalid`, passwordHash: hash('synthetic-qa-only'), name: 'Synthetic QA', maxLicenses, maxDevices, maxStudents });
    return value;
}
async function course(producerId = null) {
    const value = id('courses'); await db.createCourse({ id: value, name: 'Synthetic QA course', producerId }); return value;
}
async function moduleFor(courseId, parentId = null) {
    const value = id('modules'); await db.createModule({ id: value, courseId, parentId, name: 'Synthetic QA module' }); return value;
}
async function license(courseId, { producerId = null, studentId = null, maxDevices = 1, lotId = null } = {}) {
    const value = id('licenses'), licenseKeyHash = hash(value);
    if (studentId) await db.createLicense({ id: value, licenseKeyHash, studentId, courseId, maxDevices });
    else await db.createFreeLicense({ id: value, licenseKeyHash, courseId, maxDevices, producerId, lotId });
    return { id: value, hash: licenseKeyHash };
}
function activationInput(licenseHash, studentId, deviceId = crypto.randomUUID()) {
    return { licenseKeyHash: licenseHash, studentId, deviceId, activationTokenHash: hash(crypto.randomUUID()), maxAllowed: 3,
        expiresAt: new Date(Date.now() + 60 * 60 * 1000).toISOString() };
}

test('real PostgreSQL catalog patch preserves the HLS key and owner mappings', async () => {
    const owner = await producer(), courseId = await course(owner), moduleId = await moduleFor(courseId), videoId = id('videos');
    await db.addToCatalog({ videoId, title: 'Synthetic video', status: 'processing', sourceType: 'bunny', keyId: 'synthetic-hls-key', segmentCount: 9, courseId, producerId: owner });
    await db.moveVideoToModule(videoId, moduleId);
    await db.updateCatalogEntry({ videoId, status: 'ready' });
    const video = await db.getCatalogById(videoId);
    assert.equal(video.keyId, 'synthetic-hls-key'); assert.equal(video.segmentCount, 9); assert.equal(video.producerId, owner);
    assert.equal((await db.getCourseById(courseId)).producerId, owner);
    assert.equal((await db.getModuleById(moduleId)).producerId, owner);
    await db.addToCatalog({ videoId, title: 'Synthetic updated title', status: 'ready', sourceType: 'bunny', courseId, producerId: owner });
    assert.equal((await db.getCatalogById(videoId)).keyId, 'synthetic-hls-key');
});

test('real module relationships reject another course and recursively detach descendant videos', async () => {
    const courseId = await course(), other = await course();
    const root = await moduleFor(courseId), child = await moduleFor(courseId, root), grandchild = await moduleFor(courseId, child), leaf = await moduleFor(courseId, grandchild);
    await assert.rejects(db.createModule({ id: id('modules'), courseId: other, parentId: child, name: 'Invalid' }), { code: 'INVALID_PARENT_MODULE' });
    const videoId = id('videos'); await db.addToCatalog({ videoId, title: 'Synthetic', courseId, keyId: 'synthetic-key' });
    await assert.rejects(db.moveVideoToModule(videoId, await moduleFor(other)), { code: 'MODULE_COURSE_MISMATCH' });
    await db.moveVideoToModule(videoId, leaf); await db.deleteModule(root);
    assert.equal((await db.getCatalogById(videoId)).moduleId, null);
    assert.equal(await db.getModuleById(leaf), null);
});

test('real producer course ownership survives retries and rejects cross-tenant moves', async () => {
    const owner = await producer(), other = await producer(), courseId = await course(owner), otherCourse = await course(other), videoId = id('videos');
    await assert.rejects(db.createCourse({ id: courseId, name: 'Synthetic', producerId: other }), { code: 'COURSE_OWNER_CONFLICT' });
    await db.addToCatalog({ videoId, title: 'Synthetic', courseId, producerId: owner });
    await assert.rejects(db.moveVideoToCourse(videoId, otherCourse), { code: 'COURSE_OWNER_CONFLICT' });
    assert.equal((await db.getCatalogById(videoId)).courseId, courseId);
    assert.ok((await db.getCoursesByProducer(owner)).every(row => row.producerId === owner));
});

test('two simultaneous lot creations cannot exceed the current producer quota', async () => {
    const owner = await producer({ maxLicenses: 3, maxDevices: 1 }), courseId = await course(owner);
    const makeLot = () => ({ producerId: owner, maxLicenses: 999, lot: { id: id('lots'), courseId, maxDevices: 1 },
        licenses: Array.from({ length: 2 }, () => { const value = id('licenses'); return { id: value, hash: hash(value) }; }) });
    const results = await Promise.all([db.createProducerLotAtomic(makeLot()), db.createProducerLotAtomic(makeLot())]);
    assert.equal(results.filter(result => result.ok).length, 1);
    assert.equal(await db.countProducerLicenses(owner), 2);
    assert.equal(results.find(result => !result.ok).limit, 3);
});

test('zero quota survives persistence and allows more lots; changing to a finite cap takes effect', async () => {
    const owner = await producer({ maxLicenses: 0, maxStudents: 0, maxDevices: 1 }), courseId = await course(owner);
    assert.equal((await db.getProducerById(owner)).max_licenses, 0);
    const makeLot = () => ({ producerId: owner, lot: { id: id('lots'), courseId, maxDevices: 1 },
        licenses: Array.from({ length: 2 }, () => { const value = id('licenses'); return { id: value, hash: hash(value) }; }) });
    assert.equal((await db.createProducerLotAtomic(makeLot())).ok, true);
    assert.equal((await db.createProducerLotAtomic(makeLot())).ok, true);
    assert.equal(await db.countProducerLicenses(owner), 4);
    await db.updateProducer(owner, { max_licenses: 4 });
    assert.equal((await db.createProducerLotAtomic(makeLot())).ok, false);
    await assert.rejects(db.updateProducer(owner, { max_licenses: -1 }), { code: 'INVALID_PRODUCER_QUOTA' });
    assert.equal((await db.getProducerById(owner)).max_licenses, 4);
    await db.updateProducer(owner, { max_licenses: 0 });
    assert.equal((await db.createProducerLotAtomic(makeLot())).ok, true);
    assert.equal(await db.countProducerLicenses(owner), 6);
});

test('producer revocation is isolated, audited once and immediately denies its course while another course stays usable', async () => {
    const owner = await producer({ maxLicenses: 0 }), other = await producer(), user = await student(), device = crypto.randomUUID();
    const courseA = await course(owner), courseB = await course(owner), serialA = await license(courseA, { producerId: owner }), serialB = await license(courseB, { producerId: owner });
    const videoA = id('videos'), videoB = id('videos');
    for (const [videoId, courseId] of [[videoA, courseA], [videoB, courseB]]) await db.addToCatalog({ videoId, courseId, producerId: owner, title: 'Synthetic revocation test', status: 'ready' });
    assert.equal((await db.claimAndActivateLicenseAtomic(activationInput(serialA.hash, user, device))).ok, true);
    assert.equal((await db.claimAndActivateLicenseAtomic(activationInput(serialB.hash, user, device))).ok, true);
    const policy = createAccessPolicy({ db }), claims = { sub: user, deviceId: device };
    await policy.authorizeVideo(claims, videoA, device);
    await policy.authorizeVideo(claims, videoB, device);
    await assert.rejects(db.revokeProducerLicense({ producerId: other, licenseId: serialA.id }), { code: 'LICENSE_NOT_FOUND' });
    assert.equal((await db.getLicenseById(serialA.id)).status, 'active');
    assert.equal((await db.revokeProducerLicense({ producerId: owner, licenseId: serialA.id })).alreadyRevoked, false);
    assert.equal((await db.revokeProducerLicense({ producerId: owner, licenseId: serialA.id })).alreadyRevoked, true);
    await assert.rejects(policy.authorizeVideo(claims, videoA, device), { code: 'LICENSE_REQUIRED' });
    await policy.authorizeVideo(claims, videoB, device);
    assert.equal((await db.getLicenseById(serialB.id)).status, 'active');
    assert.equal(await db.countActiveActivationsByLicense(serialA.id), 0);
    assert.equal(await db.countActiveActivationsByLicense(serialB.id), 1);
    assert.equal(await db.countProducerLicenses(owner), 2, 'revocation never refunds the generation quota');
    const audits = (await db.pool.query("SELECT metadata FROM suspicious_activity WHERE student_id=$1 AND type='producer_license_revoked'", [user])).rows;
    assert.equal(audits.length, 1); assert.equal(JSON.parse(audits[0].metadata).licenseId, serialA.id);
    const visible = await db.getProducerLicenseItems({ producerId: owner });
    assert.equal(visible.total, 2); assert.equal(visible.rows.every(row => !('license_key_hash' in row)), true);
    assert.equal((await db.getProducerLicenseItems({ producerId: other })).total, 0);
});

test('producer batches are permanent: expiry is refused, stored dates never block playback or claims, lots report no expired count', async () => {
    const owner = await producer({ maxLicenses: 0 }), courseId = await course(owner), user = await student(), device = crypto.randomUUID();
    const expiresAt = new Date(Date.now() + 30 * 60 * 1000).toISOString(), lotId = id('lots');
    const serials = Array.from({ length: 2 }, () => { const value = id('licenses'); return { id: value, hash: hash(value) }; });
    await assert.rejects(db.createProducerLotAtomic({ producerId: owner, lot: { id: lotId, courseId, maxDevices: 1, expiresAt }, licenses: serials }), { code: 'LICENSE_EXPIRY_UNSUPPORTED' });
    await assert.rejects(db.createProducerLotAtomic({ producerId: owner, lot: { id: lotId, courseId, maxDevices: 1, durationDays: 30 }, licenses: serials }), { code: 'LICENSE_EXPIRY_UNSUPPORTED' });
    assert.equal((await db.createProducerLotAtomic({ producerId: owner, lot: { id: lotId, courseId, maxDevices: 1 }, licenses: serials })).ok, true);
    assert.equal((await db.getLicenseById(serials[0].id)).expires_at, null);
    const activation = await db.claimAndActivateLicenseAtomic(activationInput(serials[0].hash, user, device));
    assert.equal(activation.ok, true); assert.equal((await db.getLicenseById(serials[0].id)).expires_at, null, 'activation never writes a course expiry');
    const videoId = id('videos');
    await db.addToCatalog({ videoId, courseId, producerId: owner, title: 'Synthetic permanent test', status: 'ready' });
    const policy = createAccessPolicy({ db });
    await policy.authorizeVideo({ sub: user, deviceId: device }, videoId, device);
    // A legacy stored date must not lock the student out: the right to the course is permanent.
    await db.pool.query('UPDATE licenses SET expires_at=$1 WHERE lot_id=$2 AND producer_id=$3', ['2020-01-01T00:00:00.000Z', lotId, owner]);
    await policy.authorizeVideo({ sub: user, deviceId: device }, videoId, device);
    assert.equal((await db.claimAndActivateLicenseAtomic(activationInput(serials[1].hash, user, device))).ok, true);
    const lots = await db.getLotsByProducer(owner);
    assert.equal(Number(lots[0].free_count), 0); assert.equal(Number(lots[0].used_count), 2); assert.equal(lots[0].expired_count, undefined);
});

test('concurrent activation of one free serial on two devices respects the license cap', async () => {
    const courseId = await course(), user = await student(), serial = await license(courseId);
    const results = await Promise.all([
        db.claimAndActivateLicenseAtomic(activationInput(serial.hash, user)),
        db.claimAndActivateLicenseAtomic(activationInput(serial.hash, user)),
    ]);
    assert.equal(results.filter(result => result.ok).length, 1);
    assert.equal(results.find(result => !result.ok).reason, 'device_limit_exceeded');
    assert.equal(await db.countActiveActivationsByLicense(serial.id), 1);
    assert.equal((await db.getLicenseById(serial.id)).student_id, user);
    assert.ok((await db.findStudentById(user)).allowedVideos.includes(courseId));
    assert.ok((await db.getStudentCourses(user)).some(row => row.course_id === courseId));
});

test('two accounts cannot claim the same known serial', async () => {
    const courseId = await course(), first = await student(), second = await student(), serial = await license(courseId);
    const results = await Promise.all([
        db.claimAndActivateLicenseAtomic(activationInput(serial.hash, first)),
        db.claimAndActivateLicenseAtomic(activationInput(serial.hash, second)),
    ]);
    assert.equal(results.filter(result => result.ok).length, 1);
    assert.equal(results.find(result => !result.ok).reason, 'license_owner_mismatch');
    const winner = results.find(result => result.ok).license.student_id;
    const loser = winner === first ? second : first;
    assert.equal((await db.getStudentCourses(loser)).length, 0);
});

test('reactivating a revoked device cannot displace a currently active device', async () => {
    const courseId = await course(), user = await student(), serial = await license(courseId, { studentId: user });
    const firstDevice = crypto.randomUUID(), secondDevice = crypto.randomUUID();
    const first = await db.claimAndActivateLicenseAtomic(activationInput(serial.hash, user, firstDevice)); assert.equal(first.ok, true);
    await db.pool.query("UPDATE activations SET status='revoked' WHERE id=$1", [first.activationId]);
    assert.equal((await db.claimAndActivateLicenseAtomic(activationInput(serial.hash, user, secondDevice))).ok, true);
    const retry = await db.claimAndActivateLicenseAtomic(activationInput(serial.hash, user, firstDevice));
    assert.equal(retry.reason, 'device_limit_exceeded'); assert.equal(await db.countActiveActivationsByLicense(serial.id), 1);
});

test('producer student quota rejects assignment without consuming the free serial', async () => {
    const owner = await producer({ maxStudents: 1 }), courseId = await course(owner);
    await student(owner); const newcomer = await student(), serial = await license(courseId, { producerId: owner });
    const result = await db.claimAndActivateLicenseAtomic(activationInput(serial.hash, newcomer));
    assert.equal(result.reason, 'STUDENT_QUOTA_EXCEEDED');
    assert.equal((await db.getLicenseById(serial.id)).status, 'free');
    assert.equal((await db.getStudentCourses(newcomer)).length, 0);
});

test('concurrent duplicate sale notifications consume one license and retain order ownership', async () => {
    const owner = await producer(), courseId = await course(owner), user = await student();
    await license(courseId, { producerId: owner }); await license(courseId, { producerId: owner });
    const input = { courseId, studentId: user, producerId: owner, orderId: crypto.randomUUID(), customerEmail: `qa-${user}@example.invalid` };
    const results = await Promise.all([db.claimFreeLicense(input), db.claimFreeLicense(input)]);
    assert.equal(results[0].id, results[1].id);
    const count = await db.pool.query("SELECT COUNT(*) AS n FROM licenses WHERE course_id=$1 AND status='active'", [courseId]);
    assert.equal(Number(count.rows[0].n), 1);
    const otherStudent = await student();
    await assert.rejects(db.claimFreeLicense({ ...input, studentId: otherStudent, customerEmail: `qa-${otherStudent}@example.invalid` }), { code: 'ORDER_CONFLICT' });
    await assert.rejects(db.claimFreeLicense({ ...input, producerId: null, orderId: crypto.randomUUID() }), { code: 'COURSE_FORBIDDEN' });
});

test('stream operation reservation and advisory locks persist across concurrent callers', async () => {
    const courseId = await course(), operationId = id('operations');
    const input = { id: operationId, actorKey: 'admin', courseId, title: 'Synthetic', fileSize: 12, fileSha256: hash('synthetic') };
    const rows = await Promise.all([db.reserveStreamOperation(input), db.reserveStreamOperation(input)]);
    assert.equal(rows[0].id, rows[1].id);
    await db.reserveStreamOperation({ ...input, actorKey: 'producer:other', title: 'Different' });
    assert.equal((await db.getStreamOperation(operationId)).actor_key, 'admin');
    let unlock, entered;
    const gate = new Promise(resolve => { unlock = resolve; });
    const ready = new Promise(resolve => { entered = resolve; });
    const key = `synthetic-${crypto.randomUUID()}`;
    const running = db.withStreamLock(key, async () => { entered(); await gate; return true; });
    await ready;
    try { await assert.rejects(db.withStreamLock(key, async () => false), { code: 'STREAM_BUSY' }); }
    finally { unlock(); }
    assert.equal(await running, true);
    assert.equal(await db.withStreamLock(key, async () => true), true);
});

test('a short playback token can be consumed once under concurrent requests', async () => {
    const token = id('tokens'); await db.storePendingToken(token, 'synthetic-command', 'synthetic-auth', Date.now() + 30000);
    const results = await Promise.all([db.consumePendingToken(token), db.consumePendingToken(token)]);
    assert.equal(results.filter(Boolean).length, 1);
});

test('regeneration keeps commercial metadata and never unblocks an unrelated device', async () => {
    const owner = await producer(), courseId = await course(owner), user = await student(owner), lotId = id('lots');
    await db.createLot({ id: lotId, courseId, quantity: 1, producerId: owner });
    const serial = await license(courseId, { producerId: owner, lotId });
    const activation = await db.claimAndActivateLicenseAtomic(activationInput(serial.hash, user)); assert.equal(activation.ok, true);
    const order = crypto.randomUUID(); await db.pool.query('UPDATE licenses SET order_id=$1, notes=$2 WHERE id=$3', [order, 'synthetic-notes', serial.id]);
    const blockedFingerprint = crypto.randomUUID();
    await db.pool.query("INSERT INTO devices(id,student_id,fingerprint,status,first_seen,last_seen) VALUES($1,$2,$3,'blocked',$4,$4)",
        [crypto.randomUUID(), user, blockedFingerprint, new Date().toISOString()]);
    const newId = id('licenses'), newKey = 'ABCD-EFGH-JKLM-' + crypto.randomBytes(2).toString('hex').toUpperCase().replace(/[01]/g, '2');
    const previousSecret = process.env.JWT_SECRET;
    if (!process.env.JWT_SECRET || process.env.JWT_SECRET.length < 32) process.env.JWT_SECRET = crypto.randomBytes(32).toString('hex');
    let result;
    try {
        result = await db.regenerateLicense({ oldLicenseId: serial.id, newLicenseId: newId, newLicenseKey: newKey,
            newLicenseKeyHash: crypto.createHmac('sha256', process.env.JWT_SECRET).update(newKey).digest('hex') });
    } finally {
        if (previousSecret === undefined) delete process.env.JWT_SECRET; else process.env.JWT_SECRET = previousSecret;
    }
    assert.equal(result.ok, true); const regenerated = await db.getLicenseById(newId);
    assert.equal(regenerated.producer_id, owner); assert.equal(regenerated.lot_id, lotId); assert.equal(regenerated.order_id, order); assert.equal(regenerated.notes, 'synthetic-notes');
    const blocked = (await db.pool.query('SELECT status FROM devices WHERE student_id=$1 AND fingerprint=$2', [user, blockedFingerprint])).rows[0];
    assert.equal(blocked.status, 'blocked'); assert.equal(await db.countActiveActivationsByLicense(serial.id), 0);
});

test('concurrent registration retries keep one request and cannot replace a verified identity', async () => {
    const deviceId = id('registrationDevices');
    const input = { email: `qa-${deviceId}@example.invalid`, firebaseUid: crypto.randomUUID(), deviceId, name: 'Synthetic QA' };
    const ids = await Promise.all([db.createRegistrationRequest(input), db.createRegistrationRequest(input)]);
    assert.equal(ids[0], ids[1]);
    const rows = (await db.pool.query('SELECT id FROM registration_requests WHERE device_id=$1', [deviceId])).rows;
    assert.equal(rows.length, 1); assert.equal(rows[0].id, ids[0]);
    await assert.rejects(db.createRegistrationRequest({ ...input, firebaseUid: crypto.randomUUID() }), { code: 'REGISTRATION_DEVICE_OWNER_CONFLICT' });
    await assert.rejects(db.createRegistrationRequest({ ...input, email: 'other-synthetic@example.invalid' }), { code: 'REGISTRATION_DEVICE_OWNER_CONFLICT' });
});

test('concurrent public link requests preserve one shared code instead of rotating it', async () => {
    const videoId = id('videos');
    await db.addToCatalog({ videoId, title: 'Synthetic public link', status: 'ready' });
    const proposals = [crypto.randomUUID(), crypto.randomUUID()];
    const codes = await Promise.all(proposals.map(proposal => db.getOrCreatePublicCode(videoId, proposal)));
    assert.equal(codes[0], codes[1]); assert.ok(proposals.includes(codes[0]));
    assert.equal((await db.getCatalogByPublicCode(codes[0])).videoId, videoId);
    assert.equal(await db.getOrCreatePublicCode(videoId, crypto.randomUUID()), codes[0]);
    await db.pool.query("UPDATE catalog SET public_code='' WHERE video_id=$1", [videoId]);
    const replacement = crypto.randomUUID();
    assert.equal(await db.getOrCreatePublicCode(videoId, replacement), replacement);
    await assert.rejects(db.getOrCreatePublicCode(crypto.randomUUID(), crypto.randomUUID()), { code: 'VIDEO_NOT_FOUND', statusCode: 404 });
});
