'use strict';
// Disposable QA PostgreSQL only. Every write and cleanup is scoped to synthetic
// UUIDs generated by this process; legacy arrays are never migrated or replaced.
const test = require('node:test');
const { before, after } = test;
const assert = require('node:assert/strict');
const { randomUUID } = require('node:crypto');
let databaseName = '';
try { databaseName = decodeURIComponent(new URL(process.env.DATABASE_URL || '').pathname.slice(1)); } catch {}
const allowedDatabase = /^edulock_qa(?:_[a-zA-Z0-9-]+)*$/;
if (!allowedDatabase.test(databaseName)) { console.error('REFUSED: resource PostgreSQL tests require an explicitly named edulock_qa database.'); process.exit(1); }
for (const key of ['COURSES_SEED', 'CATALOG_SEED', 'CATALOG_SEED_1', 'CATALOG_SEED_2', 'CATALOG_SEED_3', 'ALLOWED_DOMAINS_SEED']) delete process.env[key];
const db = require('../database-pg');
const { createResourceRepository } = require('../lib/resource-repository');
const repo = createResourceRepository({ db });
const tracked = { protected_resources: new Set(), catalog: new Set(), modules: new Set(), courses: new Set(), producers: new Set() };
const id = table => { const value = randomUUID(); tracked[table].add(value); return value; };
const query = (...args) => db.pool.query(...args);
before(async () => {
    const actual = (await query('SELECT current_database() AS name')).rows[0].name;
    assert.equal(actual, databaseName); assert.match(actual, allowedDatabase); await db.initDb();
});
after(async () => {
    try {
        for (const table of ['protected_resources', 'catalog', 'modules', 'courses', 'producers']) {
            const values = [...tracked[table]];
            if (values.length) await query(`DELETE FROM ${table} WHERE ${table === 'catalog' ? 'video_id' : 'id'}=ANY($1::text[])`, [values]);
        }
    } finally { await db.pool.end(); }
});
async function fixture(producer = true) {
    const producerId = producer ? id('producers') : null;
    if (producerId) await query('INSERT INTO producers (id,email,name,created_at) VALUES ($1,$2,$3,$4)', [producerId, producerId + '@qa-resources.invalid', 'Synthetic resource owner', new Date().toISOString()]);
    const courseId = id('courses'), otherCourseId = id('courses'), moduleId = id('modules'), videoId = id('catalog');
    await db.createCourse({ id: courseId, name: 'Synthetic resource course', producerId });
    await db.createCourse({ id: otherCourseId, name: 'Synthetic second course', producerId });
    await db.createModule({ id: moduleId, courseId, name: 'Synthetic resource module', producerId });
    await db.addToCatalog({ videoId, title: 'Synthetic resource video', status: 'ready', courseId, producerId });
    await db.moveVideoToModule(videoId, moduleId);
    return { producerId, courseId, otherCourseId, moduleId, videoId };
}
function publicInput(f, extra = {}) { return { id: id('protected_resources'), targetKind: 'video', targetId: f.videoId, name: 'Material libre', type: 'link', protection: 'public', publicUrl: 'https://example.invalid/material.pdf', ...extra }; }
function pdfInput(f, extra = {}) { return publicInput(f, { name: 'PDF protegido', type: 'document', protection: 'protected', publicUrl: null, storageKey: randomUUID(), mimeType: 'application/pdf', byteSize: 1234, pageCount: 2, ...extra }); }
const stored = async resourceId => (await query('SELECT * FROM protected_resources WHERE id=$1', [resourceId])).rows[0];

test('create derives owner/course and returns public URL with version 1', async () => {
    const f = await fixture(); const input = publicInput(f); const resource = await repo.create(input);
    assert.equal(resource.id, input.id); assert.equal(resource.courseId, f.courseId); assert.equal(resource.producerId, f.producerId);
    assert.equal(resource.protection, 'public'); assert.equal(resource.storageKey, null); assert.equal(resource.version, 1); assert.equal(resource.deletedAt, null);
    assert.deepEqual(await repo.get(input.id.toUpperCase()), resource);
});
test('admin-owned resources with null producer work for both modules and videos', async () => {
    const f = await fixture(false); const video = await repo.create(pdfInput(f));
    const module = await repo.create(publicInput(f, { targetKind: 'module', targetId: f.moduleId }));
    assert.equal(video.producerId, null); assert.equal(module.producerId, null);
    assert.equal((await repo.resolveTarget('video', f.videoId)).moduleId, f.moduleId);
});
test('legacy document arrays remain byte-for-byte unchanged beside new resources', async () => {
    const f = await fixture(); const legacy = [{ name: 'Legacy link', url: 'https://example.invalid/free.pdf', type: 'document' }];
    await db.updateCatalogDocuments(f.videoId, legacy); await db.updateModuleDocuments(f.moduleId, legacy);
    const beforeVideo = (await query('SELECT documents FROM catalog WHERE video_id=$1', [f.videoId])).rows[0].documents;
    const beforeModule = (await query('SELECT documents FROM modules WHERE id=$1', [f.moduleId])).rows[0].documents;
    const created = await repo.create(pdfInput(f));
    await repo.update(created.id, { protection: 'public' }, { expectedVersion: 1 }); await repo.delete(created.id, { expectedVersion: 2 });
    assert.equal((await query('SELECT documents FROM catalog WHERE video_id=$1', [f.videoId])).rows[0].documents, beforeVideo);
    assert.equal((await query('SELECT documents FROM modules WHERE id=$1', [f.moduleId])).rows[0].documents, beforeModule);
    assert.deepEqual((await repo.resolveTarget('video', f.videoId)).documents, legacy);
});
test('batch list returns only selected destinations, deduplicates targets and retains stored PDF metadata', async () => {
    const f = await fixture(); const video = await repo.create(pdfInput(f));
    const module = await repo.create(publicInput(f, { targetKind: 'module', targetId: f.moduleId }));
    assert.deepEqual((await repo.listForTarget('video', f.videoId)).map(value => value.id), [video.id]);
    const rows = await repo.listForTargets([{ kind: 'video', id: f.videoId }, { kind: 'module', id: f.moduleId }, { kind: 'video', id: f.videoId }]);
    assert.deepEqual(new Set(rows.map(value => value.id)), new Set([video.id, module.id])); assert.equal(rows.length, 2);
    assert.equal(rows.find(value => value.id === video.id).byteSize, 1234); assert.deepEqual(await repo.listForTargets([]), []);
});
test('wrong supplied owner/course cannot attach resources to another producer', async () => {
    const f = await fixture();
    await assert.rejects(repo.create(publicInput(f, { producerId: randomUUID() })), { code: 'RESOURCE_TARGET_OWNER_CONFLICT' });
    await assert.rejects(repo.create(publicInput(f, { courseId: f.otherCourseId })), { code: 'RESOURCE_TARGET_OWNER_CONFLICT' });
    await assert.rejects(repo.create(publicInput(f, { producerId: null })), { code: 'RESOURCE_TARGET_OWNER_CONFLICT' });
    assert.equal((await repo.listForTarget('video', f.videoId)).length, 0);
});
test('inconsistent video, module and course owners fail closed', async () => {
    const f = await fixture();
    await query('UPDATE modules SET producer_id=NULL WHERE id=$1', [f.moduleId]);
    await assert.rejects(repo.resolveTarget('video', f.videoId), { code: 'RESOURCE_TARGET_OWNER_CONFLICT' });
    await assert.rejects(repo.resolveTarget('module', f.moduleId), { code: 'RESOURCE_TARGET_OWNER_CONFLICT' });
    await query('UPDATE modules SET producer_id=$2 WHERE id=$1', [f.moduleId, f.producerId]);
    await query('UPDATE catalog SET producer_id=NULL WHERE video_id=$1', [f.videoId]);
    await assert.rejects(repo.create(publicInput(f)), { code: 'RESOURCE_TARGET_OWNER_CONFLICT' });
});
test('missing targets and orphan modules cannot create resources', async () => {
    const f = await fixture();
    await assert.rejects(repo.create(publicInput(f, { targetId: randomUUID() })), { code: 'RESOURCE_TARGET_NOT_FOUND' });
    await query('UPDATE catalog SET course_id=NULL WHERE video_id=$1', [f.videoId]);
    await assert.rejects(repo.create(publicInput(f)), { code: 'RESOURCE_TARGET_WITHOUT_COURSE' });
    await query("UPDATE modules SET course_id='' WHERE id=$1", [f.moduleId]);
    await assert.rejects(repo.resolveTarget('module', f.moduleId), { code: 'RESOURCE_TARGET_WITHOUT_COURSE' });
});

test('standalone videos keep public links and PDF downloads without a course or module', async () => {
    for (const producerOwned of [true, false]) {
        const f = await fixture(producerOwned);
        await query('UPDATE catalog SET course_id=NULL,module_id=NULL WHERE video_id=$1', [f.videoId]);
        const target = await repo.resolveTarget('video', f.videoId);
        assert.equal(target.courseId, null); assert.equal(target.moduleId, null); assert.equal(target.producerId, f.producerId);
        const link = await repo.create(publicInput(f));
        const pdf = await repo.create(pdfInput(f, { protection: 'public' }));
        assert.equal(link.courseId, null); assert.equal(link.producerId, f.producerId);
        assert.equal(pdf.courseId, null); assert.equal(pdf.protection, 'public'); assert.equal(pdf.pageCount, 2);
        assert.deepEqual(await repo.get(link.id), link);
        assert.deepEqual(new Set((await repo.listForTarget('video', f.videoId)).map(value => value.id)), new Set([link.id, pdf.id]));
        const updated = await repo.update(link.id, { name: 'Free standalone reference' }, { expectedVersion: 1 });
        assert.equal(updated.version, 2); assert.equal(updated.protection, 'public');
    }
});

test('standalone video cannot create a protected PDF or spoof a course or owner', async () => {
    const f = await fixture();
    await query('UPDATE catalog SET course_id=NULL,module_id=NULL WHERE video_id=$1', [f.videoId]);
    await assert.rejects(repo.create(pdfInput(f)), { code: 'RESOURCE_TARGET_WITHOUT_COURSE' });
    await assert.rejects(repo.create(publicInput(f, { courseId: f.courseId })), { code: 'RESOURCE_TARGET_OWNER_CONFLICT' });
    await assert.rejects(repo.create(publicInput(f, { producerId: null })), { code: 'RESOURCE_TARGET_OWNER_CONFLICT' });
    assert.deepEqual(await repo.listForTarget('video', f.videoId), []);
});

test('standalone public PDF and link cannot become protected without assigning a course', async () => {
    const f = await fixture();
    await query('UPDATE catalog SET course_id=NULL,module_id=NULL WHERE video_id=$1', [f.videoId]);
    const pdf = await repo.create(pdfInput(f, { protection: 'public' }));
    await assert.rejects(repo.update(pdf.id, { protection: 'protected' }, { expectedVersion: 1 }), { code: 'RESOURCE_TARGET_WITHOUT_COURSE' });
    assert.deepEqual(await repo.get(pdf.id), pdf);
    const link = await repo.create(publicInput(f));
    const file = pdfInput(f);
    await assert.rejects(repo.update(link.id, { type: 'document', protection: 'protected', publicUrl: null,
        storageKey: file.storageKey, mimeType: 'application/pdf', byteSize: 1234, pageCount: 2 }, { expectedVersion: 1 }), { code: 'RESOURCE_TARGET_WITHOUT_COURSE' });
    assert.deepEqual(await repo.get(link.id), link);
});

test('standalone resource ownership and destination remain immutable after target changes', async () => {
    const f = await fixture();
    await query('UPDATE catalog SET course_id=NULL,module_id=NULL WHERE video_id=$1', [f.videoId]);
    const resource = await repo.create(publicInput(f));
    await query('UPDATE catalog SET producer_id=NULL WHERE video_id=$1', [f.videoId]);
    await assert.rejects(repo.get(resource.id), { code: 'RESOURCE_TARGET_CHANGED' });
    assert.deepEqual(await repo.listForTarget('video', f.videoId), []);
    await assert.rejects(repo.update(resource.id, { name: 'Owner takeover' }, { expectedVersion: 1 }), { code: 'RESOURCE_TARGET_CHANGED' });
    await query('UPDATE catalog SET producer_id=$2,course_id=$3 WHERE video_id=$1', [f.videoId, f.producerId, f.courseId]);
    await assert.rejects(repo.get(resource.id), { code: 'RESOURCE_TARGET_CHANGED' });
    await assert.rejects(repo.delete(resource.id, { expectedVersion: 1 }), { code: 'RESOURCE_TARGET_CHANGED' });
    assert.equal((await stored(resource.id)).course_id, null); assert.equal((await stored(resource.id)).version, 1);
});

test('PostgreSQL independently enforces a nonempty course for protected PDF resources', async () => {
    const f = await fixture(); const protectedPdf = await repo.create(pdfInput(f));
    await assert.rejects(query('UPDATE protected_resources SET course_id=NULL WHERE id=$1', [protectedPdf.id]), { code: '23514' });
    await assert.rejects(query("UPDATE protected_resources SET course_id='' WHERE id=$1", [protectedPdf.id]), { code: '23514' });
    await query('UPDATE catalog SET course_id=NULL,module_id=NULL WHERE video_id=$1', [f.videoId]);
    const publicPdf = await repo.create(pdfInput(f, { protection: 'public' }));
    await assert.rejects(query("UPDATE protected_resources SET protection='protected' WHERE id=$1", [publicPdf.id]), { code: '23514' });
    assert.equal((await stored(publicPdf.id)).protection, 'public');
});
test('moving content to another course invalidates old resource reads, lists, updates and deletes', async () => {
    const f = await fixture(); const resource = await repo.create(pdfInput(f));
    await db.moveVideoToCourse(f.videoId, f.otherCourseId);
    await assert.rejects(repo.get(resource.id), { code: 'RESOURCE_TARGET_CHANGED' });
    assert.deepEqual(await repo.listForTarget('video', f.videoId), []);
    await assert.rejects(repo.update(resource.id, { protection: 'public' }, { expectedVersion: 1 }), { code: 'RESOURCE_TARGET_CHANGED' });
    await assert.rejects(repo.delete(resource.id, { expectedVersion: 1 }), { code: 'RESOURCE_TARGET_CHANGED' });
    assert.equal((await stored(resource.id)).protection, 'protected'); assert.equal((await stored(resource.id)).deleted_at, null);
});
test('consistent takeover of an entire course does not transfer stored resource ownership', async () => {
    const f = await fixture(); const resource = await repo.create(pdfInput(f));
    await query('UPDATE courses SET producer_id=NULL WHERE id=$1', [f.courseId]);
    await query('UPDATE modules SET producer_id=NULL WHERE id=$1', [f.moduleId]);
    await query('UPDATE catalog SET producer_id=NULL WHERE video_id=$1', [f.videoId]);
    await assert.rejects(repo.get(resource.id), { code: 'RESOURCE_TARGET_CHANGED' });
    assert.deepEqual(await repo.listForTarget('video', f.videoId), []);
});
test('deleted targets never leave accessible orphan resources', async () => {
    const f = await fixture(); const resource = await repo.create(pdfInput(f));
    await query('DELETE FROM catalog WHERE video_id=$1', [f.videoId]);
    await assert.rejects(repo.get(resource.id), { code: 'RESOURCE_TARGET_NOT_FOUND' });
    assert.deepEqual(await repo.listForTarget('video', f.videoId), []);
});
test('PDF may explicitly switch Protected to Public and back without changing storage identity', async () => {
    const f = await fixture(); const original = await repo.create(pdfInput(f));
    const free = await repo.update(original.id, { protection: 'public' }, { expectedVersion: 1 });
    assert.equal(free.protection, 'public'); assert.equal(free.storageKey, original.storageKey); assert.equal(free.version, 2);
    const protectedAgain = await repo.update(original.id, { protection: 'protected' }, { expectedVersion: 2 });
    assert.equal(protectedAgain.protection, 'protected'); assert.equal(protectedAgain.publicUrl, null); assert.equal(protectedAgain.version, 3);
});
test('stale editor cannot publish a PDF after another edit changed its protection', async () => {
    const f = await fixture(); const original = await repo.create(pdfInput(f));
    await repo.update(original.id, { name: 'Revised protected document' }, { expectedVersion: 1 });
    await assert.rejects(repo.update(original.id, { protection: 'public' }, { expectedVersion: 1 }), { code: 'RESOURCE_VERSION_CONFLICT' });
    assert.equal((await repo.get(original.id)).protection, 'protected'); assert.equal((await repo.get(original.id)).version, 2);
});
test('two simultaneous edits with the same expected version produce exactly one winner', async () => {
    const f = await fixture(); const resource = await repo.create(pdfInput(f));
    const results = await Promise.allSettled([repo.update(resource.id, { name: 'Edit A' }, { expectedVersion: 1 }), repo.update(resource.id, { name: 'Edit B' }, { expectedVersion: 1 })]);
    assert.equal(results.filter(value => value.status === 'fulfilled').length, 1);
    assert.equal(results.find(value => value.status === 'rejected').reason.code, 'RESOURCE_VERSION_CONFLICT');
    assert.equal((await repo.get(resource.id)).version, 2);
});
test('missing version, immutable identity edits and invalid source changes leave the row unchanged', async () => {
    const f = await fixture(); const resource = await repo.create(pdfInput(f)); const beforeRow = await stored(resource.id);
    await assert.rejects(repo.update(resource.id, { protection: 'public' }), { code: 'RESOURCE_VERSION_REQUIRED' });
    await assert.rejects(repo.delete(resource.id), { code: 'RESOURCE_VERSION_REQUIRED' });
    await assert.rejects(repo.update(resource.id, { targetId: f.moduleId }, { expectedVersion: 1 }), { code: 'RESOURCE_INVALID_UPDATE' });
    await assert.rejects(repo.update(resource.id, { publicUrl: 'https://example.invalid/pdf' }, { expectedVersion: 1 }), { code: 'RESOURCE_PROTECTED_URL_FORBIDDEN' });
    assert.deepEqual(await stored(resource.id), beforeRow);
});
test('soft deletion advances the version, removes catalog access and preserves the audit record', async () => {
    const f = await fixture(); const resource = await repo.create(pdfInput(f));
    await assert.rejects(repo.delete(resource.id, { expectedVersion: 2 }), { code: 'RESOURCE_VERSION_CONFLICT' });
    const deleted = await repo.delete(resource.id, { expectedVersion: 1 });
    assert.equal(deleted.version, 2); assert.ok(deleted.deletedAt); assert.equal(deleted.storageKey, resource.storageKey);
    assert.equal(await repo.get(resource.id), null); assert.deepEqual(await repo.listForTarget('video', f.videoId), []);
    assert.ok((await stored(resource.id)).deleted_at);
    await assert.rejects(repo.update(resource.id, { protection: 'public' }, { expectedVersion: 2 }), { code: 'RESOURCE_NOT_FOUND' });
});
test('same storage key cannot be shared between two resources or reclaimed after soft deletion', async () => {
    const f = await fixture(); const resource = await repo.create(pdfInput(f));
    await assert.rejects(repo.create(pdfInput(f, { storageKey: resource.storageKey })), { code: 'RESOURCE_CONFLICT' });
    await repo.delete(resource.id, { expectedVersion: 1 });
    await assert.rejects(repo.create(pdfInput(f, { storageKey: resource.storageKey })), { code: 'RESOURCE_CONFLICT' });
});
test('PostgreSQL itself rejects protected URLs and missing PDF file metadata', async () => {
    const f = await fixture(); const resource = await repo.create(pdfInput(f));
    await assert.rejects(query('UPDATE protected_resources SET public_url=$2 WHERE id=$1', [resource.id, 'https://example.invalid/pdf']), { code: '23514' });
    await assert.rejects(query('UPDATE protected_resources SET page_count=NULL WHERE id=$1', [resource.id]), { code: '23514' });
    await assert.rejects(query('UPDATE protected_resources SET byte_size=26214401 WHERE id=$1', [resource.id]), { code: '23514' });
    await assert.rejects(query('UPDATE protected_resources SET page_count=201 WHERE id=$1', [resource.id]), { code: '23514' });
    assert.equal((await repo.get(resource.id)).protection, 'protected');
});
test('link to uploaded protected PDF conversion must replace all source metadata atomically', async () => {
    const f = await fixture(); const resource = await repo.create(publicInput(f));
    await assert.rejects(repo.update(resource.id, { protection: 'protected' }, { expectedVersion: 1 }), { code: 'RESOURCE_PROTECTED_URL_FORBIDDEN' });
    const file = pdfInput(f); const changed = await repo.update(resource.id, { type: 'document', protection: 'protected', publicUrl: null, storageKey: file.storageKey, mimeType: 'application/pdf', byteSize: 1234, pageCount: 2 }, { expectedVersion: 1 });
    assert.equal(changed.publicUrl, null); assert.equal(changed.version, 2); assert.equal(changed.protection, 'protected');
});
