'use strict';
const test = require('node:test'), assert = require('node:assert/strict'), fs = require('node:fs/promises'), os = require('node:os'), path = require('node:path');
const { createResourceStorage } = require('../lib/resource-storage');
test('encrypted storage persists its private key, detects tampering and never follows arbitrary paths', async () => {
    const base = await fs.mkdtemp(path.join(os.tmpdir(), 'edulock-resource-test-'));
    try {
        const storage = createResourceStorage({ directory: base }); const bytes = Buffer.from('%PDF-1.7 synthetic source');
        const id = await storage.put(bytes), file = path.join(base, id + '.enc'); const encrypted = await fs.readFile(file);
        assert.equal(encrypted.includes(bytes), false); assert.equal((await fs.readFile(path.join(base, 'master.key'))).length, 32);
        assert.deepEqual(await createResourceStorage({ directory: base }).read(id), bytes);
        encrypted[20] ^= 1; await fs.writeFile(file, encrypted); await assert.rejects(storage.read(id), { code: 'RESOURCE_INTEGRITY_FAILED' });
        await assert.rejects(storage.read('../master.key'), { code: 'RESOURCE_STORAGE_ID_INVALID' });
        await storage.discardUncommitted(id); await assert.rejects(fs.stat(file), { code: 'ENOENT' });
    } finally {
        // Resolved mkdtemp target remains a direct child of the intended temp
        // directory; only regular files generated by this test are removed.
        const real = await fs.realpath(base), parent = await fs.realpath(os.tmpdir());
        assert.equal(path.dirname(real), parent); assert.match(path.basename(real), /^edulock-resource-test-/);
        for (const entry of await fs.readdir(real, { withFileTypes: true })) { assert.ok(entry.isFile()); await fs.unlink(path.join(real, entry.name)); }
        await fs.rmdir(real);
    }
});
